DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS trainer;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS body;
DROP TABLE IF EXISTS exercise;
DROP TABLE IF EXISTS sets;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS routine;
DROP TABLE IF EXISTS ex_cat;

CREATE TABLE user (
  u_userId INTEGER PRIMARY KEY AUTOINCREMENT,
  u_name TEXT NOT NULL,
  u_password TEXT NOT NULL,
  u_trainer BIT DEFAULT 0
);

CREATE TABLE trainer (
  t_trainerId INTEGER PRIMARY KEY AUTOINCREMENT,
  t_userID INTEGER NOT NULL
);

CREATE TABLE customer (
  c_customerID INTEGER PRIMARY KEY AUTOINCREMENT,
  c_userID INTEGER NOT NULL
);

CREATE TABLE subscription (
  su_subID INTEGER PRIMARY KEY AUTOINCREMENT,
  su_customerID INTEGER NOT NULL,
  su_trainerID INTEGER NOT NULL
);

CREATE TABLE body (
  b_bodyID INTEGER PRIMARY KEY AUTOINCREMENT,
  b_userID INTEGER NOT NULL,
  b_age INTEGER NOT NULL,
  b_gender STRING, 
  b_height INTEGER,
  b_weight INTEGER
);

CREATE TABLE exercise(
  e_exerciseID INTEGER PRIMARY KEY AUTOINCREMENT,
  e_name STRING NOT NULL
);
CREATE TABLE sets(
  s_setID INTEGER PRIMARY KEY AUTOINCREMENT,
  s_reps INTEGER, 
  s_weight INTEGER, 
  s_duration INTEGER
);
CREATE TABLE category(
  c_categoryID INTEGER PRIMARY KEY AUTOINCREMENT,
  c_name STRING NOT NULL
);
CREATE TABLE routine(
  r_sessionID INTEGER PRIMARY KEY AUTOINCREMENT,
  r_userID INTEGER NOT NULL, 
  r_status BIT default 0, 
  r_datecreatedm DATE, 
  r_datecompleted DATE 
);
CREATE TABLE ex_cat(
  ec_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ec_categoryID INTEGER NOT NULL,
   ec_exerciseID INTEGER NOT NULL
);