CREATE TABLE IF NOT EXISTS user (
  u_userId INTEGER PRIMARY KEY AUTOINCREMENT,
  u_name TEXT NOT NULL,
  u_password TEXT NOT NULL,
  u_trainer BIT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS  trainer (
  t_trainerId INTEGER PRIMARY KEY AUTOINCREMENT,
  t_userID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS  customer (
  c_customerID INTEGER PRIMARY KEY AUTOINCREMENT,
  c_userID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS subscription (
  su_subID INTEGER PRIMARY KEY AUTOINCREMENT,
  su_customerID INTEGER NOT NULL,
  su_trainerID INTEGER NOT NULL
);